# 3 tasks, first task failed with onError: continue
## 2nd task (onError:fail) has resource dependency, 3rd task has order dependency
## => task1 fail, task 2,3 not scheduled, pipelinerun fail

apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: resource-dep-
spec:
  pipelineSpec:
    tasks:
      - name: task1
        onError: continue
        taskSpec:
          results:
          - name: suffix
          steps:
          - name: step1
            image: alpine
            script: |
              echo -n "suffix" > $(results.suffix.path)
              exit 1
      - name: task2
        runAfter: [task1]
        taskSpec:
          params:
          - name: arg
          steps:
          - name: step1
            image: alpine
            script: |
              exit 0
        params:
        - name: arg
          value: "prefix:$(tasks.task1.results.suffix)"
      - name: task3
        runAfter: [task2]
        taskSpec:
          steps:
          - name: step1
            image: alpine
            script: |
              exit 0              

---
# 3 tasks, first task failed with onError: continue
## 2nd task (onError:continue) has resource dependency, 3rd task has order dependency
## => task1 fail, task 2 skipped, task3 skipped, pipelinerun success
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: resource-dep-continue-
spec:
  pipelineSpec:
    tasks:
      - name: task1
        onError: continue
        taskSpec:
          results:
          - name: suffix
          steps:
          - name: step1
            image: alpine
            script: |
              echo -n "suffix" > $(results.suffix.path)
              exit 1
      - name: task2
        runAfter: [task1]
        onError: continue
        taskSpec:
          params:
          - name: arg
          steps:
          - name: step1
            image: alpine
            script: |
              exit 0
        params:
        - name: arg
          value: "prefix:$(tasks.task1.results.suffix)"
      - name: task3
        runAfter: [task2]
        taskSpec:
          steps:
          - name: step1
            image: alpine
            script: |
              exit 0              

---
# 3 tasks, first task failed with onError: continue
## 2nd task (onError:continue) has resource dependency, 3rd task has resource dependency
## => task1 fail, task 2 skipped, task3 skipped, pipelinerun success
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: resource-dep-continue-
spec:
  pipelineSpec:
    tasks:
      - name: task1
        onError: continue
        taskSpec:
          results:
          - name: suffix
          steps:
          - name: step1
            image: alpine
            script: |
              echo -n "suffix" > $(results.suffix.path)
              exit 1
      - name: task2
        onError: continue
        taskSpec:
          params:
          - name: arg
          results:
          - name: suffix
          steps:
          - name: step1
            image: alpine
            script: |
              echo "$(params.arg)" > $(results.suffix.path)
              exit 1
        params:
        - name: arg
          value: "prefix:$(tasks.task1.results.suffix)"
      - name: task3
        taskSpec:
          params:
          - name: arg
          results:
          - name: suffix
          steps:
          - name: step1
            image: alpine
            script: |
              echo "$(params.arg)" > $(results.suffix.path)
              exit 0       
        params:
        - name: "arg"
          value: "prefix:$(tasks.task2.results.suffix)"
      - name: task4
        taskSpec:
          params:
          - name: arg
          steps:
          - name: step1
            image: alpine
            script: |
              echo "$(params.arg)"
              exit 0       
        params:
        - name: "arg"
          value: "prefix:$(tasks.task3.results.suffix)"