apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-param-enum
spec:
  params:
  - name: message
    enum: ["v1", "v2", "v3"]
    default: "v1"
  tasks:
  - name: task1
    params:
      - name: message
        value: $(params.message)
    taskSpec:
      params:
      - name: message
      steps:
      - name: build
        image: bash:3.2
        script: |
          echo "$(params.message)"
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipelinerun-param-enum
spec:
  pipelineRef:
    name: pipeline-param-enum
  params:
    - name: message
      value: "v2"
